language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -U setuptools"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install shapely"   # used to verify __geo_interface__
  - "pip install ."
script:
  coverage run --source=karta tests/runtests.py
after_success:
  coveralls
sudo: false
