language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - libproj-dev   # otherwise gdal raises an error

before_install:
  - "wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh"
  - "chmod +x miniconda.sh"
  - "./miniconda.sh -b"
  - "export PATH=/home/travis/miniconda2/bin:$PATH"
  - "conda update --yes conda"
  - "conda info -a"

install:
  - "conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pip gdal"
  - "source activate test-environment"
    #- "pip install -U setuptools"
  - "pip install coveralls"
  - "pip install Cython"
  - "pip install -r requirements.txt"
  - "pip install shapely"   # used to verify __geo_interface__
  - "pip install ."

script:
  coverage run --source=karta tests/runtests.py

after_success:
  coveralls

sudo:   # container-based testing
  false
