language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
branches:
  only:
    - master
    - travis
before_install:
  #- sudo apt-get update --quiet
  #- sudo apt-get install --assume-yes python-numpy cython python3-numpy
install:
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script: python karta/tests/test_runner.py
