language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
branches:
  only:
    - master
    - travis
before-install:
  - sudo apt-get update -q
  - sudo apt-get install numpy cython pyproj
install:
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script: python karta/tests/test_runner.py
